import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen grid place-items-center">
      {children}
    </main>
  );
}
