import type { Metadata } from "next";
import "@/scss/main.scss";
import { default as SessionWrapper } from "@/components/session/wrapper";
import { Header } from "@/components/partials/navbar";
import { montserrat, plusJakartaSans } from "@/components/fonts";
import { NextProgressBar } from "@/components/loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} ${montserrat.variable}`}>
        <NextProgressBar />
        <Header />
        <SessionWrapper>
          {children}
        </SessionWrapper>
      </body>
    </html>
  );
}
