import "@/scss/main.scss";

import type { Metadata } from "next";

import { montserrat, plusJakartaSans } from "@/components/fonts";
import { NextProgressBar } from "@/components/loader";
import { Header } from "@/components/partials/navbar";
import { default as SessionWrapper } from "@/components/session/wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} ${montserrat.className}`}>
        <NextProgressBar />
        <Header />
        <SessionWrapper>
          <main>{children}</main>
        </SessionWrapper>
      </body>
    </html>
  );
}
